name: first_worklow
on: push
jobs:
  test_and_lints:
    runs-on: ubuntu-latest
    steps:
    - name: get the code
      uses: actions/checkout@v3 
    - name: install dependenies
      run: npm ci
    - name: Run test script
      run: npm run test
    - name: Run Lints script
      run: npm run lint
    - name: building
      run: npm run build
  Deploy:
    needs: [test_and_lints]
    runs-on: ubuntu-latest
    steps:
    - name: get the code
      uses: actions/checkout@v3 
    - name: build project
      run: echo "Deploying ... . ."



